# Generated by Django 3.2.7 on 2021-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
    ]
