# Generated by Django 3.2.7 on 2021-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_university_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
